import { Product, Category } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Oxford Classic Shirt',
    category: Category.SHIRTS,
    price: 89,
    image: 'https://picsum.photos/id/1059/800/1000',
    description: 'A timeless staple for every wardrobe. This Oxford shirt features premium cotton construction and a tailored fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  {
    id: '2',
    name: 'Selvedge Slim Jeans',
    category: Category.JEANS,
    price: 145,
    image: 'https://picsum.photos/id/103/800/1000',
    description: 'Japanese denim with a modern slim cut. Durable, stylish, and built to last.',
    sizes: ['30', '32', '34', '36'],
    featured: true,
  },
  {
    id: '3',
    name: 'Midnight Bomber Jacket',
    category: Category.JACKETS,
    price: 220,
    image: 'https://picsum.photos/id/1005/800/1000',
    description: 'Sleek midnight blue bomber jacket. Water-resistant outer shell with a comfortable lining.',
    sizes: ['M', 'L', 'XL'],
    featured: true,
  },
  {
    id: '4',
    name: 'Leather Chelsea Boots',
    category: Category.SHOES,
    price: 180,
    image: 'https://picsum.photos/id/1070/800/1000',
    description: 'Handcrafted leather boots that elevate any outfit. Features a durable rubber sole.',
    sizes: ['8', '9', '10', '11', '12'],
  },
  {
    id: '5',
    name: 'Wool Blend Suit',
    category: Category.SUITS,
    price: 450,
    image: 'https://picsum.photos/id/1001/800/1000',
    description: 'Charcoal grey wool blend suit. Perfect for formal occasions and business settings.',
    sizes: ['38R', '40R', '42R', '44R'],
    featured: true,
  },
  {
    id: '6',
    name: 'Minimalist Watch',
    category: Category.ACCESSORIES,
    price: 120,
    image: 'https://picsum.photos/id/1018/800/1000',
    description: 'Clean design with a genuine leather strap. Water resistant up to 50m.',
    sizes: ['One Size'],
  },
   {
    id: '7',
    name: 'Linen Summer Shirt',
    category: Category.SHIRTS,
    price: 75,
    image: 'https://picsum.photos/id/1058/800/1000',
    description: 'Breathable linen shirt perfect for hot summer days.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
   {
    id: '8',
    name: 'Distressed Denim Jacket',
    category: Category.JACKETS,
    price: 110,
    image: 'https://picsum.photos/id/1012/800/1000',
    description: 'Vintage wash denim jacket with light distressing for a lived-in look.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
];
